name: Lint Code Base

on:
  push:
    branches-ignore:
      - "dependabot/**"

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .*css/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_HTML: false
          VALIDATE_MARKDOWN: false

